### ISSUE TITLE
Permission denied on trying to pull docker image?

### ISSUE THREAD

**Issue by tsjain** [jcrodriguez1989/tf_blog_autokeras#1]
I get a permission denied message on trying to execute the following command

docker pull jcrodriguez1989/r-autokeras:0.1.0

**Comment by jcrodriguez1989** [comment]
Hi @tsjain ,
I would need some more information to reproduce your issue.
Can you pull other docker images? For instance:

```bash
docker pull r-base
```

**Comment by tsjain** [comment]
Thanks for the quick response. I tried running the command with "sudo", and I was able to pull the image. Thanks, again.
